# Generated by Django 4.2.11 on 2026-08-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_updated_at_workerprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='experience',
            field=models.CharField(choices=[('1 Month', '1 Month'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('6 Months', '6 Months'), ('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('5 Years', '5 Years'), ('More than 5 Years', 'More than 5 Years')], default='1 Year', max_length=30),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='name',
            field=models.CharField(default='Unknown Worker', max_length=100),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='phone',
            field=models.CharField(default='Not Provided', max_length=15),
        ),
    ]
