# Generated by Django 4.2.11 on 2026-09-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='worker_profile_photos/'),
        ),
    ]
