# Generated by Django 4.2.11 on 2026-09-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_workerprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='area',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
