# Generated by Django 4.2.11 on 2026-09-10 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_rating_rating_unique_complaint_rating_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='inactive', max_length=20)),
                ('first_month_price', models.PositiveIntegerField(default=49)),
                ('monthly_price', models.PositiveIntegerField(default=149)),
                ('razorpay_customer_id', models.CharField(blank=True, default='', max_length=100)),
                ('razorpay_subscription_id', models.CharField(blank=True, default='', max_length=100)),
                ('razorpay_plan_id', models.CharField(blank=True, default='', max_length=100)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('terms_version', models.CharField(default='1.0', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('next_billing_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='complaints.workerprofile')),
            ],
        ),
    ]
