# Generated by Django 4.2.11 on 2026-09-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_workersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='completion_otp',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='complaint',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
