# Generated by Django 4.2.11 on 2026-09-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0015_chatmessage_edit_count_chatmessage_edited_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='after_photo',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_after_photos/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='after_photo_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
