# Generated by Django 4.2.11 on 2026-09-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0016_complaint_after_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('High', 'High Priority'), ('Emergency', 'Emergency')], default='Normal', max_length=20),
        ),
    ]
