# Generated by Django 4.2.11 on 2026-09-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0017_complaint_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='aadhaar_back_photo',
            field=models.ImageField(blank=True, null=True, upload_to='worker_verification/aadhaar_back/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='aadhaar_front_photo',
            field=models.ImageField(blank=True, null=True, upload_to='worker_verification/aadhaar_front/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='aadhaar_last4',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='admin_verification_note',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='probation_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='probation_target',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='skill_category',
            field=models.CharField(choices=[('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Carpenter', 'Carpenter'), ('Cleaner', 'Cleaner'), ('Painter', 'Painter'), ('Mason', 'Mason'), ('AC/Refrigeration', 'AC / Refrigeration Technician'), ('Appliance Repair', 'Appliance Repair Technician'), ('General Technician', 'General Technician'), ('Other', 'Other')], default='General Technician', max_length=50),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='verification_status',
            field=models.CharField(choices=[('Pending', 'Pending Verification'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Suspended', 'Suspended')], default='Approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='worker_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
