# Generated by Django 4.2.11 on 2026-09-14 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0019_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPayoutDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_method', models.CharField(blank=True, choices=[('upi', 'UPI'), ('bank', 'Bank Account')], default='', max_length=20)),
                ('upi_id', models.CharField(blank=True, default='', max_length=150)),
                ('account_holder_name', models.CharField(blank=True, default='', max_length=150)),
                ('bank_name', models.CharField(blank=True, default='', max_length=150)),
                ('bank_account_last4', models.CharField(blank=True, default='', max_length=4)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=11)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_details', to='complaints.workerprofile')),
            ],
        ),
    ]
