from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
        (
            "complaints",
            "0026_workerfollow_workerprofilelike",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AIMonthlyBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "budget_inr",
                    models.DecimalField(
                        decimal_places=4,
                        default=100,
                        max_digits=12,
                    ),
                ),
                (
                    "total_reserved_inr",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=12,
                    ),
                ),
                (
                    "total_spent_inr",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=12,
                    ),
                ),
                (
                    "free_reserved_inr",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=12,
                    ),
                ),
                (
                    "free_spent_inr",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=12,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-year",
                    "-month",
                ],
            },
        ),
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            (
                                "complaint_analysis",
                                "Complaint Analysis",
                            ),
                            (
                                "translation",
                                "Translation",
                            ),
                            (
                                "category_suggestion",
                                "Category Suggestion",
                            ),
                            (
                                "detailed_analysis",
                                "Detailed Complaint Analysis",
                            ),
                            (
                                "worker_summary",
                                "Worker Complaint Summary",
                            ),
                            (
                                "worker_reply",
                                "Worker Reply Generator",
                            ),
                            (
                                "photo_analysis",
                                "Photo Analysis",
                            ),
                            (
                                "help_chat",
                                "AI Help Chat",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            (
                                "free",
                                "Free Citizen",
                            ),
                            (
                                "citizen_premium",
                                "Citizen Premium",
                            ),
                            (
                                "worker_free",
                                "Free Worker",
                            ),
                            (
                                "worker_pro",
                                "Worker Pro",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "reserved",
                                "Reserved",
                            ),
                            (
                                "success",
                                "Success",
                            ),
                            (
                                "failed",
                                "Failed",
                            ),
                        ],
                        default="reserved",
                        max_length=20,
                    ),
                ),
                (
                    "credit_cost",
                    models.PositiveSmallIntegerField(
                        default=1,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                    ),
                ),
                (
                    "request_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                    ),
                ),
                (
                    "reserved_cost_inr",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=12,
                    ),
                ),
                (
                    "estimated_cost_inr",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=12,
                    ),
                ),
                (
                    "input_tokens",
                    models.PositiveIntegerField(
                        default=0,
                    ),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(
                        default=0,
                    ),
                ),
                (
                    "total_tokens",
                    models.PositiveIntegerField(
                        default=0,
                    ),
                ),
                (
                    "response_json",
                    models.JSONField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=80,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=
                            django.db.models.deletion.CASCADE,
                        related_name=
                            "ai_usage_logs",
                        to=
                            settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-created_at",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="aimonthlybudget",
            constraint=models.UniqueConstraint(
                fields=(
                    "year",
                    "month",
                ),
                name="unique_ai_monthly_budget",
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(
                fields=[
                    "user",
                    "status",
                    "created_at",
                ],
                name="ai_user_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(
                fields=[
                    "feature",
                    "created_at",
                ],
                name="ai_feature_time_idx",
            ),
        ),
    ]
