from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
        (
            "complaints",
            "0027_ai_credit_cost_guard",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPremiumMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "inactive",
                                "Inactive",
                            ),
                            (
                                "active",
                                "Active",
                            ),
                            (
                                "expired",
                                "Expired",
                            ),
                        ],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=79,
                        max_digits=8,
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "last_paid_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "last_razorpay_payment_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                    ),
                ),
                (
                    "renewal_count",
                    models.PositiveIntegerField(
                        default=0,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=
                            django.db.models.deletion.CASCADE,
                        related_name=
                            "citizen_premium_membership",
                        to=
                            settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="user_premium_membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=
                    django.db.models.deletion.SET_NULL,
                related_name=
                    "payment_transactions",
                to=
                    "complaints.userpremiummembership",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="payment_for",
            field=models.CharField(
                choices=[
                    (
                        "complaint",
                        "Complaint / Service",
                    ),
                    (
                        "worker_subscription",
                        "Worker Subscription",
                    ),
                    (
                        "citizen_premium",
                        "Citizen Premium",
                    ),
                    (
                        "other",
                        "Other",
                    ),
                ],
                default="other",
                max_length=30,
            ),
        ),
    ]
