# Generated by Django 4.2.11 on 2026-09-22 22:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0031_worker_subscription_plan_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('business_type', models.CharField(choices=[('retail', 'Retail Shop'), ('company', 'Company / Office'), ('restaurant', 'Restaurant'), ('warehouse', 'Warehouse'), ('service', 'Service Business'), ('other', 'Other')], default='other', max_length=30)),
                ('contact_person', models.CharField(max_length=100)),
                ('business_phone', models.CharField(blank=True, default='', max_length=15)),
                ('business_email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='', max_length=500)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('about', models.TextField(blank=True, default='', max_length=2000)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='job_marketplace/employer_logos/')),
                ('registration_number', models.CharField(blank=True, default='', max_length=100)),
                ('gst_number', models.CharField(blank=True, default='', max_length=30)),
                ('website_url', models.URLField(blank=True, default='')),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='job_marketplace/employer_verification/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20)),
                ('verification_note', models.CharField(blank=True, default='', max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['business_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_note', models.TextField(blank=True, default='', max_length=1500)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('offer_received', 'Offer Received'), ('hired', 'Hired'), ('rejected', 'Not Selected'), ('withdrawn', 'Withdrawn')], db_index=True, default='applied', max_length=30)),
                ('employer_note', models.TextField(blank=True, default='', max_length=1500)),
                ('interview_scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('interview_location', models.CharField(blank=True, default='', max_length=255)),
                ('interview_note', models.CharField(blank=True, default='', max_length=500)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('shortlisted_at', models.DateTimeField(blank=True, null=True)),
                ('hired_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='JobEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('ended', 'Ended')], db_index=True, default='active', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employment', to='complaints.jobapplication')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('required_skill', models.CharField(blank=True, default='', max_length=100)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('daily', 'Daily Work')], default='full_time', max_length=20)),
                ('description', models.TextField(max_length=5000)),
                ('requirements', models.TextField(blank=True, default='', max_length=3000)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('salary_period', models.CharField(choices=[('hour', 'Per Hour'), ('day', 'Per Day'), ('week', 'Per Week'), ('month', 'Per Month'), ('year', 'Per Year'), ('fixed', 'Fixed Amount')], default='month', max_length=20)),
                ('salary_is_negotiable', models.BooleanField(default=False)),
                ('vacancies', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('location_name', models.CharField(max_length=200)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('work_timing', models.CharField(blank=True, default='', max_length=120)),
                ('weekly_off', models.CharField(blank=True, default='', max_length=120)),
                ('joining_note', models.CharField(blank=True, default='', max_length=160)),
                ('experience_required', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('paused', 'Paused'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='complaints.employerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerJobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available_for_jobs', models.BooleanField(db_index=True, default=False)),
                ('headline', models.CharField(blank=True, default='', max_length=160)),
                ('bio', models.TextField(blank=True, default='', max_length=1500)),
                ('preferred_job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('daily', 'Daily Work'), ('any', 'Any')], default='any', max_length=20)),
                ('preferred_city', models.CharField(blank=True, default='', max_length=100)),
                ('preferred_area', models.CharField(blank=True, default='', max_length=150)),
                ('expected_salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('show_linkedin_to_employers', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_profile', to='complaints.workerprofile')),
            ],
            options={
                'ordering': ['-is_available_for_jobs', 'worker__name'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_workers', to='complaints.jobpost')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='complaints.workerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('employer_to_worker', 'Employer to Worker'), ('worker_to_employer', 'Worker to Employer')], max_length=30)),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, default='', max_length=1500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='complaints.jobemployment')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_job_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('salary_period', models.CharField(choices=[('hour', 'Per Hour'), ('day', 'Per Day'), ('week', 'Per Week'), ('month', 'Per Month'), ('year', 'Per Year'), ('fixed', 'Fixed Amount')], default='month', max_length=20)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, default='', max_length=120)),
                ('work_location', models.CharField(max_length=255)),
                ('terms', models.TextField(max_length=4000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='complaints.jobapplication')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='JobChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='', max_length=2000)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='job_marketplace/chat_attachments/')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='complaints.jobapplication')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_job_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='complaints.jobpost'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='complaints.workerprofile'),
        ),
        migrations.AddConstraint(
            model_name='savedjob',
            constraint=models.UniqueConstraint(fields=('worker', 'job'), name='unique_saved_job_per_worker'),
        ),
        migrations.AddConstraint(
            model_name='jobreview',
            constraint=models.UniqueConstraint(fields=('employment', 'review_type'), name='unique_job_review_type'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['status', 'created_at'], name='complaints__status_59ea0b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['city', 'status'], name='complaints__city_0cbf23_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['category', 'status'], name='complaints__categor_915d66_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['employer', 'status'], name='complaints__employe_fef4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='jobchatmessage',
            index=models.Index(fields=['application', 'created_at'], name='complaints__applica_01d6f7_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status'], name='complaints__job_id_2cd81d_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['worker', 'status'], name='complaints__worker__23b04b_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('job', 'worker'), name='unique_worker_job_application'),
        ),
        migrations.AddIndex(
            model_name='employerprofile',
            index=models.Index(fields=['verification_status', 'is_active'], name='complaints__verific_1a0030_idx'),
        ),
        migrations.AddIndex(
            model_name='employerprofile',
            index=models.Index(fields=['city', 'is_active'], name='complaints__city_5f8a32_idx'),
        ),
    ]
